### ISSUE TITLE
Bow draw y axis is shifted down

### ISSUE THREAD

**Issue by shrobbyy** [Legacy-Visuals-Project/Animatium#2]
Using the old item holding doesn't make the bow drawing exactly accurate to 1.7

**Comment by Mixces** [comment]
> Using the old item holding doesn't make the bow drawing exactly accurate to 1.7

Could you provide screenshots or a video?

**Comment by Mixces** [comment]
> > Using the old item holding doesn't make the bow drawing exactly accurate to 1.7
> 
> Could you provide screenshots or a video?

Furthermore, are you using the latest build? And do you have the TiltItemPositions feature enabled?

This is how the bow looks for me in 1.21.4:
![2024-12-21_10 45 11](https://github.com/user-attachments/assets/f217e763-7a0f-4850-932d-88c61abc07c6)
This is how it looks in 1.7.10:
![2024-12-21_10 39 54](https://github.com/user-attachments/assets/22378ec8-2783-41e2-a963-98d30e9a452f)

The only plausible difference here are a few pixels being holes.

**Comment by shrobbyy** [comment]
> > > Using the old item holding doesn't make the bow drawing exactly accurate to 1.7
> > 
> > 
> > Could you provide screenshots or a video?
> 
> Furthermore, are you using the latest build? And do you have the TiltItemPositions feature enabled?
> 
> This is how the bow looks for me in 1.21.4: ![2024-12-21_10 45 11](https://private-user-images.githubusercontent.com/70869960/397941103-f217e763-7a0f-4850-932d-88c61abc07c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDAxOTcsIm5iZiI6MTczNDc5OTg5NywicGF0aCI6Ii83MDg2OTk2MC8zOTc5NDExMDMtZjIxN2U3NjMtN2EwZi00ODUwLTkzMmQtODhjNjFhYmMwN2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE2NTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NjUwY2I3MWY4ZDUzMzMxNDgyY2E5YTIwNDZmNzkzNmQ4YTkyNTliNTcxMWRkYzViMzViZjYyYThkNDhlMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvdhSoXWENqZyG2T4Pt2EGr86ocomVmjhDftrpC4UIg) This is how it looks in 1.7.10: ![2024-12-21_10 39 54](https://private-user-images.githubusercontent.com/70869960/397941115-22378ec8-2783-41e2-a963-98d30e9a452f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDAxOTcsIm5iZiI6MTczNDc5OTg5NywicGF0aCI6Ii83MDg2OTk2MC8zOTc5NDExMTUtMjIzNzhlYzgtMjc4My00MWUyLWE5NjMtOThkMzBlOWE0NTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE2NTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMTljMGUyYTRhNDEzYmI3ODIzNDY4NThmZmNjZTk4ZDdiZTMwYWMwZmVlYzgxOTFlOWQ3YWVkZTM2ZDE3ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DbPUjfVxW1HT5M_bI99rIN1-bTRYBr_Q0LuHdyxOdOs)
> 
> The only plausible difference here are a few pixels being holes.

Huh, interesting.. I thought it happend because of my additional installed mods, but I've tried it with only Animatium and the bow was still wrong. There might be a conflict within the mod's settings itself.

**Comment by lowercasebtw** [comment]
Try a fresh settings, delete the settings file

**Comment by shrobbyy** [comment]
Odd, that actually helped. Thanks!

**Comment by lowercasebtw** [comment]
:)
